### ISSUE TITLE
Error: Cannot find module 'mqtt'

### ISSUE THREAD

**Issue by lowgoz** [the1laz/cgateweb#15]
Heyhey - love your work
Have re-installed a few times with different guides / versions of things and keep coming across the below error when trying to get the service working. Have you any ideas?!

pi@raspberrypi:/usr/local/bin/cgateweb $ sudo node index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'mqtt'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/bin/cgateweb/index.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by the1laz** [comment]
Hi, looks like you need to go into /usr/local/bin/cgateweb and run 
```
npm install
```
Sorry, just noticed it's missing from the instructions.

**Comment by lowgoz** [comment]
you sir, are a champion

for anyone else having this error, i had to "sudo apt-get install npm" as well as running npm install (as mentioned above) as sudo. Doing this resolved all issues !

**Comment by the1laz** [comment]
No problem, good to hear it's working.

**Comment by deo651** [comment]
Could you please provide some details of the operations on windows? I cannot understand your linux command. Thanks.
