### ISSUE TITLE
Hey Hi!!! Is it necessary to install npm if rpi already has latest npm?

### ISSUE THREAD

**Issue by pete173** [the1laz/cgateweb#21]

**Comment by pete173** [comment]
hi
is it necessary to install npm if npm is already installed?

cd /usr/local/bin
sudo git clone https://github.com/the1laz/cgateweb.git
cd cgateweb
npm install-------------------------> is this step necessary.. I already have latest npm
sudo nano settings.js

**Comment by the1laz** [comment]
Nope, shouldn't need to install it if you've already got it installed.

**Comment by pete173** [comment]
These are the errors..i dont understand this
[19:47:14] root@openhab:/usr/local/bin/cgateweb# node index.js
/usr/local/bin/cgateweb/index.js:37
var client = mqtt.createClient(mqtt_url.port, mqtt_url.hostname,OPTIONS);
                  ^

TypeError: mqtt.createClient is not a function
    at Object.<anonymous> (/usr/local/bin/cgateweb/index.js:37:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by pete173** [comment]
hi mqtt dependency was not there..thanks

**Comment by the1laz** [comment]
Oh, sorry, just reread that. npm install doesn't install npm, it installs the dependencies, so you do need to run that.

**Comment by pete173** [comment]
I ran node i it fixed the issue🙂...now everthing is working fine..you have done a great work👍....thanks
