### ISSUE TITLE
cgateweb goes to sleep

### ISSUE THREAD

**Issue by garethcook** [the1laz/cgateweb#29]
I'm running cgate and cgateweb on a Pi 3, nothing else, to surface mqtt to Home Assistant on another Pi. When it works, it works very well and responsive.

What we're seeing tho is that it's an unreliable solution, and I'm trying to understand why, and testing would suggest it's cgateweb not talking to cgate on the same machine. The address is listed as 127.0.0.1

When the system is unresponsive, I'm seeing no read MQTT traffic using mqttexplorer from cgateweb. At the same time, I can from a Windows PC happily talk to cgate on the Pi so we know the transport from the CNI to cgate is working as expected. A quick restart of cgateweb gets things going again. I can write MQTT traffic back.

In summary : more often than not, cgateweb isn't reporting CBUS changes (such as a light being turned on), but can continue to write changes (so it can tell a light to turn on). 

Is there a way of debugging the link between cgateweb and cgate better to understand where the break happens? Thanks

**Comment by the1laz** [comment]
Probably the way to start would be to change logging to true in settings.J's, then check the output on journalctl -u cgateweb.service

You should be able to see the commands you're sending and the feedback from cgate.

**Comment by garethcook** [comment]
Decided the Home Bridge image must be the issue, I used an old Pi 2 and installed just cgate, ser2sock and cgateweb. All working perfectly except that working with Toolkit to this instance of cgate was sooo slow. We're talking 10 mins up update an eDLT

Thought I'd install it all on a Pi 4 which has a VPN server on, same procedure I thought expect I'm now seeing this when starting cgateweb. Any ideas? Node version is 14.8.3 (also tried v17) and NPM is 8.1.2

pi@PIVPN:/usr/local/bin/cgateweb $ node index.js 
/usr/local/bin/cgateweb/index.js:37
var client = mqtt.createClient(mqtt_url.port, mqtt_url.hostname,OPTIONS);
                  ^

TypeError: mqtt.createClient is not a function
    at Object.<anonymous> (/usr/local/bin/cgateweb/index.js:37:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by garethcook** [comment]
So I stopped using that Pi, it was also running Home Bridge. Having started with a fresh blank Pi, I'm finding that the mqtt code isn't being found. 

Steps are:
Install Raspbian Lite
Apt get update and upgrade
Sudo su
curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
sudo apt install nodejs
(it's not installed by default)
sudo apt install git
sudo npm install
sudo npm audit fix --force

Then test cgateweb can even run before we configure setting.js:
cd /usr/local/bin/cgateweb
node index.js
(Complains mqtt isn’t a function at this point - node index.js won’t run) TypeError: mqtt.createClient is not a function
So something's missing. I've tried installing npm mqtt, installing different versions of node and npm, but not getting very far :-(

**Comment by garethcook** [comment]
Node 17 wasn't the way to go. This process works:
>Install Raspbian - Buster lite
Sudo apt get update
sudo apt full-upgrade
Sudo su
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
sudo apt-get install -y nodejs
sudo apt install git
sudo npm install forever -g
cd /usr/local/bin
sudo git clone https://github.com/the1laz/cgateweb.git
sudo chown -R pi:pi cgateweb
cd cgateweb
sudo npm install
Then edit settings.js

(Then install java, cgate, ser2sock, etc)

**Comment by garethcook** [comment]
I think the culprit is actually cgate. I'll be back with more.

**Comment by awonglk** [comment]
I get that "TypeError: mqtt.createClient" when I use a newer version of MQTT. This "upgrade" of MQTT version happened as NPM was warning about "severe vulnerability".
So i guess for that error to go away, you'll need to downgrade MQTT version to the one expected in package.json

**Comment by rbswift** [comment]
> I get that "TypeError: mqtt.createClient" when I use a newer version of MQTT. This "upgrade" of MQTT version happened as NPM was warning about "severe vulnerability".
> So i guess for that error to go away, you'll need to downgrade MQTT version to the one expected in package.json

This is fixed in my branch / PR.

There's also a PR to periodically send a heartbeat NoOp which I've added to my branch.
